apiVersion: v1
kind: Service
metadata:
  labels:
    app: model
  name: model
spec:
  ports:
  - name: app
    nodePort: 30100 # This can be omitted and will be auto-assigned if not specified.
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: metrics
    nodePort: 30101 # This can be omitted and will be auto-assigned if not specified.
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: model
  type: NodePort
status:
  loadBalancer: {}
